package com.emberinn.app.ui.theme

import androidx.compose.ui.graphics.Color

// 暖纸色浅色（默认）+ 墨暖深色 —— 余烬美学
val EmberPrimaryLight = Color(0xFF9A4A2A)
val EmberOnPrimaryLight = Color(0xFFFFFFFF)
val EmberPrimaryContainerLight = Color(0xFFFFDBCF)
val EmberOnPrimaryContainerLight = Color(0xFF3A0B00)
val EmberSecondaryLight = Color(0xFF77574A)
val EmberOnSecondaryLight = Color(0xFFFFFFFF)
val EmberSecondaryContainerLight = Color(0xFFFFDBCF)
val EmberOnSecondaryContainerLight = Color(0xFF2C160C)
val EmberTertiaryLight = Color(0xFF6B5C2D)
val EmberOnTertiaryLight = Color(0xFFFFFFFF)
val EmberTertiaryContainerLight = Color(0xFFF4E0A8)
val EmberOnTertiaryContainerLight = Color(0xFF221A00)
val EmberBackgroundLight = Color(0xFFFFF8F5)
val EmberOnBackgroundLight = Color(0xFF221A16)
val EmberSurfaceLight = Color(0xFFFFF8F5)
val EmberOnSurfaceLight = Color(0xFF221A16)
val EmberSurfaceVariantLight = Color(0xFFF3E7E1)
val EmberOnSurfaceVariantLight = Color(0xFF52443E)
val EmberOutlineLight = Color(0xFF85736C)

val EmberPrimaryDark = Color(0xFFFFB59B)
val EmberOnPrimaryDark = Color(0xFF5C1600)
val EmberPrimaryContainerDark = Color(0xFF7A2F12)
val EmberOnPrimaryContainerDark = Color(0xFFFFDBCF)
val EmberSecondaryDark = Color(0xFFE7BEB0)
val EmberOnSecondaryDark = Color(0xFF442B20)
val EmberSecondaryContainerDark = Color(0xFF5D4135)
val EmberOnSecondaryContainerDark = Color(0xFFFFDBCF)
val EmberTertiaryDark = Color(0xFFD7C58E)
val EmberOnTertiaryDark = Color(0xFF3A2F00)
val EmberTertiaryContainerDark = Color(0xFF52451B)
val EmberOnTertiaryContainerDark = Color(0xFFF4E0A8)
val EmberBackgroundDark = Color(0xFF16110F)
val EmberOnBackgroundDark = Color(0xFFEFDFD9)
val EmberSurfaceDark = Color(0xFF1E1815)
val EmberOnSurfaceDark = Color(0xFFEFDFD9)
val EmberSurfaceVariantDark = Color(0xFF52443E)
val EmberOnSurfaceVariantDark = Color(0xFFD7C2BA)
val EmberOutlineDark = Color(0xFF9F8C84)
