package com.emberinn.app.ui.theme

import androidx.compose.ui.graphics.Color

/** 预设主题：seed 生成整套 M3 配色。24 套 = 11 基础 + 7 艺术向（电影感/星夜/油画/水墨/深海/胶片/霓虹）
 *  + 6 画廊系列（金冕·巴洛克骷髅王 / 玄骑·黑甲白马 / 赤月·红月孤影 / 安魂·白袍玫瑰 / 沧溟·碧海神阶 / 禁忌档案馆）。
 *  艺术扩展字段（contrast/gem/metal/texture/auraTop）把古典油画语言落进 UI：
 *  明暗对照法、宝石点缀、金属工艺、底材纹理（TextureSpec 六图元自由配方）、天空氛围。
 *  浅色不再当"白纸"：lightBg 是主题氛围的日间版（天青釉/旧画布/羊皮纸/海雾），深浅同性格。 */
data class ThemePreset(
    val id: String,
    val name: String,
    val desc: String,
    val seed: Color,
    val secondary: Color,
    val tertiary: Color,
    val lightBg: Color,
    val darkBg: Color,
    /** 六套主题各自性格——形状语言随预设变化（墨韵圆润/丹砂方正/琉璃浑圆）。 */
    val shape: String = "default",
    /** 间距节奏倍数（>1 更松散，<1 更紧凑）；默认 1.0。 */
    val spacing: Float = 1f,
    /** 动效速度倍数（>1 更快，<1 更慢）；默认 1.0。 */
    val motionScale: Float = 1f,
    // ---- 官方 SillyTavern 字段默认值（null=跟随 M3 自动生成；酒馆官方主题填官方真值） ----
    val stBody: Color? = null,
    val stEm: Color? = null,
    val stUnderline: Color? = null,
    val stQuote: Color? = null,
    val stUserBubble: Color? = null,
    val stBotBubble: Color? = null,
    val stBorder: Color? = null,
    val stShadow: Color? = null,
    val stBlurTint: Color? = null,
    // ---- M3 角色覆盖（酒馆官方主题填官方 SmartTheme 真值；null=由 seed 生成） ----
    val schemePrimary: Color? = null,
    val schemeSecondary: Color? = null,
    val schemeTertiary: Color? = null,
    val schemeBackground: Color? = null,
    val schemeOnBackground: Color? = null,
    val schemeSurface: Color? = null,
    val schemeOnSurface: Color? = null,
    // ---- 艺术向扩展（古典油画/黑暗奇幻主题语言；默认值 = 不启用，兼容官方与角色卡动态主题） ----
    /** 明暗对照（chiaroscuro）：>1 容器色阶梯拉开、光影更戏剧化；默认 1 = M3 原节奏。 */
    val contrast: Float = 1f,
    /** 宝石点缀色：红宝石/蓝宝石/星尘——氛围光晕与预览宝石位（null=不启用）。 */
    val gem: Color? = null,
    /** 金属工艺色：古金/旧银/青铜——主题卡描边与装饰细节（null=不启用）。 */
    val metal: Color? = null,
    /** 底材纹理配方：六图元（织纹/布点/排线/交叉排线/纤维/颗粒）任意组合，各主题自由定制。 */
    val texture: TextureSpec = TextureSpec(),
    /** 天空氛围色：深色模式页面顶部极淡渐变天色——红月、烟雾战场（null=不启用）。 */
    val auraTop: Color? = null,
    /** 浅色模式天空氛围：象牙晨光、绯色薄暮等（null=浅色不画天空）。 */
    val auraTopLight: Color? = null,
)

val ThemePresets: List<ThemePreset> = listOf(
    // 默认主题：旧暖白全面换冷净纸白，朱砂提饱和，深色底压成纯炭黑
    ThemePreset(
        id = "ink",
        name = "墨韵",
        desc = "宣纸冷白 · 朱砂一点",
        seed = Color(0xFFD9382B),
        secondary = Color(0xFF4A4A4F),
        tertiary = Color(0xFF2E5A73),
        lightBg = Color(0xFFF6F1E9),
        darkBg = Color(0xFF131314),
        shape = "rounded",
        spacing = 1.12f,
        motionScale = 0.85f,
        stBody = Color(0xFFD4D4D2),
        stEm = Color(0xFF8E8E90),
        stUnderline = Color(0xFFE8A79D),
        stQuote = Color(0xFFE0604F),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D343436),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF1A1A1C),
        schemePrimary = Color(0xFFFF6A57),
        schemeSecondary = Color(0xFFB0B0B5),
        schemeTertiary = Color(0xFF7FAFD0),
        // 水墨画：宣纸草筋纤维 + 微尘，冷银提亮 + 顶部墨青天，朱砂是唯一宝石
        contrast = 1.1f,
        gem = Color(0xFFE8604F),
        metal = Color(0xFFAEB2B6),
        texture = TextureSpec(fiber = 1f, stipple = 0.4f, grain = 0.25f),
        auraTop = Color(0xFF1B2224),
        auraTopLight = Color(0xFFE2E8E4),
    ),
    ThemePreset(
        id = "celadon",
        name = "青瓷",
        desc = "雨过天青 · 翠色欲滴",
        seed = Color(0xFF0E9F6E),
        secondary = Color(0xFF4E6660),
        tertiary = Color(0xFFB08A3E),
        lightBg = Color(0xFFE9F1ED),
        darkBg = Color(0xFF0E1512),
        shape = "rounded",
        spacing = 1.05f,
        motionScale = 0.95f,
        stBody = Color(0xFFC9CECC),
        stEm = Color(0xFF7C8B88),
        stUnderline = Color(0xFFA1C4BC),
        stQuote = Color(0xFF3FC48C),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D2E3431),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF14201A),
        schemePrimary = Color(0xFF35C98F),
        schemeSecondary = Color(0xFF8FA8A0),
        schemeTertiary = Color(0xFFC9AC70),
        // 瓷器：釉面光滑是身份——全场唯一无纹理的彩色主题，天青夜做顶光
        contrast = 1.05f,
        gem = Color(0xFF3FC48C),
        metal = Color(0xFFC9AC70),
        auraTop = Color(0xFF183038),
        auraTopLight = Color(0xFFEBDCC0),
    ),
    ThemePreset(
        id = "night",
        name = "夜航",
        desc = "深海夜蓝 · 灯塔琥珀",
        seed = Color(0xFFE8992E),
        secondary = Color(0xFF54687C),
        tertiary = Color(0xFF2E4A70),
        lightBg = Color(0xFFE7EDF5),
        darkBg = Color(0xFF0B111C),
        shape = "default",
        stBody = Color(0xFFC6CBD2),
        stEm = Color(0xFF7D8995),
        stUnderline = Color(0xFFE7CAA0),
        stQuote = Color(0xFFF0B04C),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D2A2E38),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF101826),
        schemePrimary = Color(0xFFF5B04A),
        schemeSecondary = Color(0xFF8B9BB0),
        schemeTertiary = Color(0xFF6E93C4),
        // 透纳海景油画：画布织纹 + 海盐颗粒，黄铜器件 + 深海夜幕天，灯塔琥珀是宝石
        contrast = 1.2f,
        gem = Color(0xFFF0B04C),
        metal = Color(0xFFB8935A),
        texture = TextureSpec(weave = 0.85f, grain = 0.4f),
        auraTop = Color(0xFF16263D),
        auraTopLight = Color(0xFFEBE1D0),
    ),
    ThemePreset(
        id = "cinnabar",
        name = "丹砂",
        desc = "方赤印章 · 掷地有声",
        seed = Color(0xFFCC3324),
        secondary = Color(0xFF8A5A44),
        tertiary = Color(0xFFB08A3E),
        lightBg = Color(0xFFF6EBE4),
        darkBg = Color(0xFF191011),
        shape = "square",
        spacing = 0.92f,
        motionScale = 1.15f,
        stBody = Color(0xFFCDC7C5),
        stEm = Color(0xFFA17B69),
        stUnderline = Color(0xFFE6A8A0),
        stQuote = Color(0xFFEE6B55),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D362824),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF201315),
        schemePrimary = Color(0xFFFF7057),
        schemeSecondary = Color(0xFFC29882),
        schemeTertiary = Color(0xFFCDA85E),
        // 篆刻金石：蚀刻排线 60° + 交叉 = 刀刻痕，印泥朱做宝石、刻石白做金属，暗绛夜天
        contrast = 1.25f,
        gem = Color(0xFFC43A2B),
        metal = Color(0xFFD8CFC5),
        texture = TextureSpec(hatch = 0.9f, crossHatch = 0.45f, hatchAngle = 60f, stipple = 0.3f),
        auraTop = Color(0xFF2A1214),
    ),
    ThemePreset(
        id = "glaze",
        name = "琉璃",
        desc = "霓虹紫蓝 · 玻璃质感",
        seed = Color(0xFF5B5DF7),
        secondary = Color(0xFF2EA8B8),
        tertiary = Color(0xFF9B5CF6),
        lightBg = Color(0xFFEEF0FB),
        darkBg = Color(0xFF0F1019),
        shape = "circle",
        spacing = 0.95f,
        motionScale = 1.05f,
        stBody = Color(0xFFC8CAD1),
        stEm = Color(0xFF65B9C6),
        stUnderline = Color(0xFFB5BDFF),
        stQuote = Color(0xFF8D90FF),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D2B2D3C),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF141624),
        schemePrimary = Color(0xFF8E90FF),
        schemeSecondary = Color(0xFF5AC8D8),
        schemeTertiary = Color(0xFFB587FF),
        // 玻璃器：通体光滑无纹理（第二无纹主题，紫蓝与青瓷区分），高反差 + 紫蓝夜天
        contrast = 1.3f,
        gem = Color(0xFFB587FF),
        metal = Color(0xFF5AC8D8),
        auraTop = Color(0xFF1B1435),
        auraTopLight = Color(0xFFE2DCEC),
    ),
    ThemePreset(
        id = "paper",
        name = "石墨",
        desc = "黑白灰阶 · 极简克制",
        seed = Color(0xFF3E4045),
        secondary = Color(0xFF6B6E74),
        tertiary = Color(0xFF8A8F98),
        lightBg = Color(0xFFF0F0F3),
        darkBg = Color(0xFF111113),
        shape = "default",
        stBody = Color(0xFFCCCCCC),
        stEm = Color(0xFF8B8B8E),
        stUnderline = Color(0xFFB5B5B7),
        stQuote = Color(0xFFA8AAAF),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D323236),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF18181A),
        schemePrimary = Color(0xFFB8BCC4),
        schemeSecondary = Color(0xFF93969C),
        schemeTertiary = Color(0xFFA6ABB5),
        // 石墨素描：铅笔排线 30° + 交叉 + 炭粉颗粒，全场唯一无宝石无金属（极简即身份），高反差黑白
        contrast = 1.2f,
        texture = TextureSpec(hatch = 0.55f, crossHatch = 0.3f, hatchAngle = 30f, grain = 0.6f),
        auraTop = Color(0xFF1E1E22),
        auraTopLight = Color(0xFFE9E9E7),
    ),
    // 酒馆官方（SillyTavern 1.18 默认 SmartTheme，public/style.css :root 逐值核对）：
    // 墨黑底 #171717 · 象牙文字 rgb(220,220,210) · 次要 rgb(145,145,145)
    // 青绿点缀 rgb(188,231,207) · 引用橙 rgb(225,138,36) · Noto Sans 15px / Noto Sans Mono
    ThemePreset(
        id = "st",
        name = "酒馆官方",
        desc = "SillyTavern 默认配色，逐值还原",
        seed = Color(0xFF7FAF8C),
        secondary = Color(0xFF919191),
        tertiary = Color(0xFFE18A24),
        lightBg = Color(0xFFEDEBE2),
        darkBg = Color(0xFF171717),
        shape = "default",
        stBody = Color(0xFFDCDCD2),
        stEm = Color(0xFF919191),
        stUnderline = Color(0xFFBCE7CF),
        stQuote = Color(0xFFE18A24),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D3C3C3C),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF171717),
        schemePrimary = Color(0xFFE18A24),
        schemeSecondary = Color(0xFF919191),
        schemeTertiary = Color(0xFFBCE7CF),
        schemeBackground = Color(0xFF171717),
        schemeOnBackground = Color(0xFFDCDCD2),
        schemeSurface = Color(0xFF171717),
        schemeOnSurface = Color(0xFFDCDCD2),
    ),
    ThemePreset(
        id = "bamboo",
        name = "竹青",
        desc = "竹影扫阶 · 苔色沉静",
        seed = Color(0xFF3E9B5F),
        secondary = Color(0xFF74855F),
        tertiary = Color(0xFFC9A227),
        lightBg = Color(0xFFEAF0E4),
        darkBg = Color(0xFF101A13),
        shape = "rounded",
        spacing = 1.05f,
        motionScale = 0.95f,
        stBody = Color(0xFFC8CEC8),
        stEm = Color(0xFF95A28C),
        stUnderline = Color(0xFFAFCCBD),
        stQuote = Color(0xFF5ABF7E),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D2A3229),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF152119),
        schemePrimary = Color(0xFF5ECB84),
        schemeSecondary = Color(0xFF9DAD8A),
        schemeTertiary = Color(0xFFD8B955),
        // 竹园晨雾：宣纸纤维 = 竹叶长丝 + 雾尘，竹黄宝石 + 苔色金属，黛绿夜天
        contrast = 1.05f,
        gem = Color(0xFFD8B955),
        metal = Color(0xFF9DAD8A),
        texture = TextureSpec(fiber = 0.8f, stipple = 0.35f, grain = 0.2f),
        auraTop = Color(0xFF182518),
        auraTopLight = Color(0xFFE0E8DA),
    ),
    ThemePreset(
        id = "dusk",
        name = "暮紫",
        desc = "暮色四合 · 紫气东来",
        seed = Color(0xFF8450E0),
        secondary = Color(0xFF9A6FB0),
        tertiary = Color(0xFFE08A5A),
        lightBg = Color(0xFFEFE9F7),
        darkBg = Color(0xFF161022),
        shape = "rounded",
        stBody = Color(0xFFCDC8D2),
        stEm = Color(0xFFAE8CC0),
        stUnderline = Color(0xFFC4B6E2),
        stQuote = Color(0xFFA98FDF),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D302842),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF1C1528),
        schemePrimary = Color(0xFFAB86EE),
        schemeSecondary = Color(0xFFC2A2D2),
        schemeTertiary = Color(0xFFF0A172),
        // 暮霭水彩：暮尘布点 + 水彩颗粒，落日橙宝石 + 淡紫银金属，紫暮天做顶
        contrast = 1.15f,
        gem = Color(0xFFF0A172),
        metal = Color(0xFFC2A2D2),
        texture = TextureSpec(stipple = 0.6f, grain = 0.45f),
        auraTop = Color(0xFF231733),
        auraTopLight = Color(0xFFF0DCC6),
    ),
    ThemePreset(
        id = "mist",
        name = "晨雾",
        desc = "雾锁寒江 · 天光微亮",
        seed = Color(0xFF4478B8),
        secondary = Color(0xFF7D94A8),
        tertiary = Color(0xFFB08D57),
        lightBg = Color(0xFFE8EFF4),
        darkBg = Color(0xFF101722),
        shape = "default",
        motionScale = 0.95f,
        stBody = Color(0xFFC8CDD3),
        stEm = Color(0xFF97A9B9),
        stUnderline = Color(0xFFB7C5D6),
        stQuote = Color(0xFF7FA8D6),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D28303C),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF151E2A),
        schemePrimary = Color(0xFF84AEDE),
        schemeSecondary = Color(0xFF9FB4C8),
        schemeTertiary = Color(0xFFC9AC77),
        // 雾锁寒江：全场唯一低反差（0.9，雾把明暗压平），晨光金宝石 + 雾蓝金属；
        // 纹理 = 雾滴布点 + 湿颗粒（水汽最重的底材）
        contrast = 0.9f,
        gem = Color(0xFFC9AC77),
        metal = Color(0xFF9FB4C8),
        texture = TextureSpec(stipple = 0.7f, grain = 0.5f, intensity = 0.8f),
        auraTop = Color(0xFF1D2A38),
        auraTopLight = Color(0xFFEFE6D0),
    ),
    ThemePreset(
        id = "sakura",
        name = "樱粉",
        desc = "樱吹雪落 · 绯色温柔",
        seed = Color(0xFFE05590),
        secondary = Color(0xFFB58A8E),
        tertiary = Color(0xFF8E7CC3),
        lightBg = Color(0xFFF9EFF1),
        darkBg = Color(0xFF1D1218),
        shape = "rounded",
        spacing = 1.05f,
        motionScale = 1.05f,
        stBody = Color(0xFFD0C8CD),
        stEm = Color(0xFFC4A1A5),
        stUnderline = Color(0xFFE7BCCB),
        stQuote = Color(0xFFF08AA9),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D3A2A32),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF241620),
        schemePrimary = Color(0xFFF095B0),
        schemeSecondary = Color(0xFFCFACA8),
        schemeTertiary = Color(0xFFAA9BDC),
        // 樱吹雪：落瓣布点（稀疏大点）+ 花瓣纤维，樱绯宝石 + 粉银金属，暮樱紫天
        contrast = 1.05f,
        gem = Color(0xFFF08AA9),
        metal = Color(0xFFCFACA8),
        texture = TextureSpec(stipple = 0.5f, fiber = 0.3f, scale = 1.5f),
        auraTop = Color(0xFF2A1626),
        auraTopLight = Color(0xFFF2DFD8),
    ),
    // ---- 艺术向主题：每套围绕一种绘画/影像语言展开，冷暖对撞比基础 11 套更戏剧化 ----
    // 电影感黄昏：琥珀熔金压在深蓝夜幕上，冷影暖光的经典 teal & orange 对撞
    ThemePreset(
        id = "molten",
        name = "熔金",
        desc = "落日熔金 · 暮云合璧",
        seed = Color(0xFFE8842B),
        secondary = Color(0xFF54687A),
        tertiary = Color(0xFFC2452E),
        lightBg = Color(0xFFF8EED9),
        darkBg = Color(0xFF131A20),
        shape = "rounded",
        spacing = 1.08f,
        motionScale = 0.9f,
        stBody = Color(0xFFD2CFC8),
        stEm = Color(0xFF9C968C),
        stUnderline = Color(0xFFE2C49A),
        stQuote = Color(0xFFF2A65A),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D262830),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF182028),
        schemePrimary = Color(0xFFF5A55C),
        schemeSecondary = Color(0xFF96A8BC),
        schemeTertiary = Color(0xFFE07058),
        // 电影感：粗画布织纹（大尺）+ 胶片颗粒——影院画幅的颗粒底
        contrast = 1.15f,
        gem = Color(0xFFD0542E),
        metal = Color(0xFFDFAE62),
        texture = TextureSpec(weave = 1f, grain = 0.45f, scale = 1.35f),
        auraTop = Color(0xFF22303C),
        auraTopLight = Color(0xFFF2D9A6),
    ),
    // 梦境星夜：靛蓝垂到近黑，主色是月光下的长春花蓝，tertiary 取星尘青
    ThemePreset(
        id = "indigo",
        name = "靛夜",
        desc = "靛夜垂幕 · 星尘微光",
        seed = Color(0xFF6B7CFF),
        secondary = Color(0xFF4A5A8A),
        tertiary = Color(0xFF8FD8E8),
        lightBg = Color(0xFFECEEF9),
        darkBg = Color(0xFF0C1024),
        shape = "circle",
        spacing = 1.05f,
        motionScale = 0.95f,
        stBody = Color(0xFFC6C8D8),
        stEm = Color(0xFF7E86A8),
        stUnderline = Color(0xFFA8B2E8),
        stQuote = Color(0xFF8E9BFF),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D232A45),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF111530),
        schemePrimary = Color(0xFF97A5FF),
        schemeSecondary = Color(0xFF7386C0),
        schemeTertiary = Color(0xFF9ADCEA),
        // 星夜：星尘布点（随机疏密）+ 微颗粒——梵高星点的夜空底
        contrast = 1.15f,
        gem = Color(0xFF7FD8EA),
        metal = Color(0xFFAEB6D8),
        texture = TextureSpec(stipple = 0.65f, grain = 0.3f, scale = 1.3f),
        auraTop = Color(0xFF141B3D),
        auraTopLight = Color(0xFFD8DCF0),
    ),
    // 古典油画：烛光琥珀 + 熟褐 + 威尼斯红，底色像上了年纪的画布
    ThemePreset(
        id = "amber",
        name = "琥珀",
        desc = "烛光琥珀 · 旧世油画",
        seed = Color(0xFFB4702A),
        secondary = Color(0xFF7A5C42),
        tertiary = Color(0xFF8A3B2E),
        lightBg = Color(0xFFF6EBD5),
        darkBg = Color(0xFF1A130C),
        shape = "rounded",
        spacing = 1.15f,
        motionScale = 0.85f,
        stBody = Color(0xFFD8CCC0),
        stEm = Color(0xFFA88F78),
        stUnderline = Color(0xFFDCB888),
        stQuote = Color(0xFFD89A56),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D32261A),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF201811),
        schemePrimary = Color(0xFFDFA05A),
        schemeSecondary = Color(0xFFB59070),
        schemeTertiary = Color(0xFFCB6E58),
        // 旧世油画：老画布粗织纹（大尺）+ 龟裂颗粒——伦勃朗底子的年龄感
        contrast = 1.2f,
        gem = Color(0xFF8A3B2E),
        metal = Color(0xFFC89A58),
        texture = TextureSpec(weave = 0.95f, grain = 0.3f, scale = 1.5f),
        auraTop = Color(0xFF2A1C0E),
        auraTopLight = Color(0xFFF0DEB6),
    ),
    // 水墨山水：雾青灰 + 墨黑 + 芦苇枯金，最慢的动效（motionScale 0.8）配最松的留白
    ThemePreset(
        id = "inkwash",
        name = "黛山",
        desc = "远山如黛 · 雾隐寒江",
        seed = Color(0xFF5A7A78),
        secondary = Color(0xFF6E7A80),
        tertiary = Color(0xFF9A8B6E),
        lightBg = Color(0xFFECF0EC),
        darkBg = Color(0xFF121717),
        shape = "default",
        spacing = 1.18f,
        motionScale = 0.8f,
        stBody = Color(0xFFC8CCCA),
        stEm = Color(0xFF8A938F),
        stUnderline = Color(0xFFAAB8B4),
        stQuote = Color(0xFF84A8A2),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D22292B),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF171D1D),
        schemePrimary = Color(0xFF8FB2AE),
        schemeSecondary = Color(0xFF97A0A6),
        schemeTertiary = Color(0xFFB3A584),
        // 黛山：宣纸纤维最重（草筋横陈）+ 雾尘——生宣吸水的毛边感
        contrast = 1.05f,
        gem = Color(0xFFB3A584),
        metal = Color(0xFF9FAAA6),
        texture = TextureSpec(fiber = 1f, stipple = 0.3f, intensity = 0.9f),
        auraTop = Color(0xFF1E2626),
        auraTopLight = Color(0xFFDCE3DF),
    ),
    // 深海幽光：万米以下的黑青，主色是发光的浮游生物青绿，tertiary 是透进水面的浅青
    ThemePreset(
        id = "abyss",
        name = "深海",
        desc = "万米深蓝 · 幽光浮游",
        seed = Color(0xFF1FA8A0),
        secondary = Color(0xFF3D5A70),
        tertiary = Color(0xFF4FC3E8),
        lightBg = Color(0xFFE4EFF0),
        darkBg = Color(0xFF071417),
        shape = "circle",
        spacing = 1f,
        motionScale = 1f,
        stBody = Color(0xFFC2CDCD),
        stEm = Color(0xFF6F8A8C),
        stUnderline = Color(0xFF8FBBB8),
        stQuote = Color(0xFF45C8BE),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D182A30),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF0B1A1E),
        schemePrimary = Color(0xFF3EC8BE),
        schemeSecondary = Color(0xFF5F8098),
        schemeTertiary = Color(0xFF6CC8E8),
        contrast = 1.25f,
        gem = Color(0xFF4FE0D0),
        metal = Color(0xFFB8C8CC),
        // 深海：浮游生物光斑（稀疏大点）+ 悬浮微粒——水柱里的浮游层
        texture = TextureSpec(stipple = 0.4f, grain = 0.25f, scale = 1.8f),
        auraTop = Color(0xFF0A2430),
        auraTopLight = Color(0xFFC6DEE4),
    ),
    // 复古胶片：柯达褪色的暖棕 + 灰青阴影，像抽屉里放旧的照片
    ThemePreset(
        id = "film",
        name = "胶片",
        desc = "柯达褪色 · 旧梦微尘",
        seed = Color(0xFFC08A5A),
        secondary = Color(0xFF7A858A),
        tertiary = Color(0xFFB0655A),
        lightBg = Color(0xFFF5ECDD),
        darkBg = Color(0xFF16181A),
        shape = "default",
        spacing = 1.02f,
        motionScale = 0.95f,
        stBody = Color(0xFFCDC8C0),
        stEm = Color(0xFF9A948C),
        stUnderline = Color(0xFFCBB49A),
        stQuote = Color(0xFFD0A074),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D25262A),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF1B1D1F),
        schemePrimary = Color(0xFFD2A274),
        schemeSecondary = Color(0xFF9AA4A8),
        schemeTertiary = Color(0xFFC4837A),
        // 胶片：银盐颗粒全场最重 + 相纸微尘——Kodak Portra 的感光颗粒
        contrast = 1.1f,
        gem = Color(0xFFC46B5A),
        metal = Color(0xFFA8A8A0),
        texture = TextureSpec(grain = 1f, stipple = 0.3f),
        auraTop = Color(0xFF23262B),
        auraTopLight = Color(0xFFEAD8C2),
    ),
    // 雨夜霓虹：湿沥青路面反射品红/青双色霓虹，方正利落、动效更快
    ThemePreset(
        id = "neon",
        name = "霓虹",
        desc = "湿街倒影 · 霓虹未熄",
        seed = Color(0xFFE84FA0),
        secondary = Color(0xFF2EA8C5),
        tertiary = Color(0xFF8A5CF0),
        lightBg = Color(0xFFF1EDF5),
        darkBg = Color(0xFF101017),
        shape = "square",
        spacing = 0.95f,
        motionScale = 1.1f,
        stBody = Color(0xFFCCC8D2),
        stEm = Color(0xFF8A8494),
        stUnderline = Color(0xFFE0A0C8),
        stQuote = Color(0xFFFF6EB8),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D292038),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF15121E),
        schemePrimary = Color(0xFFFF6EB8),
        schemeSecondary = Color(0xFF46C0DC),
        schemeTertiary = Color(0xFFA37AFF),
        contrast = 1.3f,
        gem = Color(0xFFFF5FB8),
        metal = Color(0xFF46C0DC),
        auraTop = Color(0xFF1A1024),
        auraTopLight = Color(0xFFE8D8EE),
    ),
    // ---- 画廊系列：五幅画 + 一座档案馆 = 六套主题，同一世界观 ----
    // ① 猩红王座：骷髅王 + 巴洛克银金铠甲 + 红蓝宝石 + 黑披风猩红内衬 + 暗青烟雾战场。
    //    深色=黑曜石王座厅、古金主色、猩红宝石光、暗青战场天；浅色=象牙白画布上的古金与猩红撞色
    ThemePreset(
        id = "crown",
        name = "猩红王座",
        desc = "骸骨加冕 · 巴洛克金工",
        seed = Color(0xFFC9A24B),
        secondary = Color(0xFF8E9086),
        tertiary = Color(0xFF9E2B25),
        lightBg = Color(0xFFF5EED8),
        darkBg = Color(0xFF0B0A0D),
        shape = "rounded",
        spacing = 1.15f,
        motionScale = 0.9f,
        stBody = Color(0xFFD8D2C0),
        stEm = Color(0xFF94968A),
        stUnderline = Color(0xFFC9B47E),
        stQuote = Color(0xFFD9B96C),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D1E2826),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF10191B),
        schemePrimary = Color(0xFFD4A94F),
        schemeSecondary = Color(0xFFADAE9F),
        schemeTertiary = Color(0xFFC4574A),
        // 巴洛克王座厅：宫廷粗织挂毯（大尺）+ 金粉颗粒——鲁本斯画布的浮华
        contrast = 1.3f,
        gem = Color(0xFFD0342C),
        metal = Color(0xFFC9A24B),
        texture = TextureSpec(weave = 1f, grain = 0.35f, scale = 1.6f),
        auraTop = Color(0xFF16333A),
        auraTopLight = Color(0xFFE8CE8E),
    ),
    // ② 白鹰圣殿：白色战马 + 巨型白鹰 + 黑甲骑士 + 白色大理石悬崖圣殿 + 暗红披风。
    //    深色=月夜圣殿、象牙白主色（白马白鹰）、暗红宝石、蓝灰夜空；浅色=大理石白 + 钢蓝撞色 + 象牙晨光
    ThemePreset(
        id = "knight",
        name = "白鹰圣殿",
        desc = "玄甲白翼 · 悬崖圣殿",
        seed = Color(0xFF4A688C),
        secondary = Color(0xFF5C6670),
        // 暗红（披风与宝石）——骑士的荣誉之血
        tertiary = Color(0xFFA63830),
        lightBg = Color(0xFFEDEFEA),
        darkBg = Color(0xFF10141B),
        shape = "square",
        spacing = 1.1f,
        motionScale = 0.95f,
        stBody = Color(0xFFC8CCD2),
        stEm = Color(0xFF8A93A0),
        stUnderline = Color(0xFFA9B0B8),
        stQuote = Color(0xFFB8483C),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D222830),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF151A22),
        schemePrimary = Color(0xFFD9DDE2),
        schemeSecondary = Color(0xFF7C8B9A),
        schemeTertiary = Color(0xFFB4433A),
        // 大理石圣殿：云纹长纤维（大尺缓弯）+ 石粉颗粒——米开朗基罗的大理石肌理
        contrast = 1.25f,
        gem = Color(0xFFB4362B),
        metal = Color(0xFFB8BEC6),
        texture = TextureSpec(fiber = 0.55f, grain = 0.4f, scale = 1.6f),
        auraTop = Color(0xFF1F2C3E),
        auraTopLight = Color(0xFFE9E4D2),
    ),
    // ③ 赤月森林：巨大血月 + 垂直黑剪影 + 绯红森林 + 白色悬崖。
    //    极度有限的红黑色调是灵魂——深色=血月主色配黑幕；浅色=暖象牙月光 + 绯红撞色 + 绯薄暮天
    ThemePreset(
        id = "vermilion",
        name = "赤月森林",
        desc = "血月孤影 · 绯林千丈",
        seed = Color(0xFFC7301F),
        // 枯金（悬崖古遗迹）与月象牙——红黑世界仅有的两种"光"
        secondary = Color(0xFFA88C5C),
        tertiary = Color(0xFFD9C79E),
        lightBg = Color(0xFFF7E9D3),
        darkBg = Color(0xFF150709),
        shape = "circle",
        spacing = 1.2f,
        motionScale = 0.8f,
        stBody = Color(0xFFC9BEB2),
        stEm = Color(0xFF97867C),
        stUnderline = Color(0xFFB08A7E),
        stQuote = Color(0xFFD8402C),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D2A1114),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF180A0C),
        schemePrimary = Color(0xFFE05238),
        schemeSecondary = Color(0xFFA88C5C),
        schemeTertiary = Color(0xFFD9C79E),
        // 赤月：血月浮尘（布点+颗粒，暖色底上如炭火余烬飘浮）
        contrast = 1.35f,
        gem = Color(0xFFE04A30),
        metal = Color(0xFFDCC9A0),
        texture = TextureSpec(stipple = 0.7f, grain = 0.35f, scale = 1.4f),
        auraTop = Color(0xFF4A0F0C),
        auraTopLight = Color(0xFFF2C4A0),
    ),
    // ④ 亡者圣堂：白袍骷髅 + 兜下纯黑虚空 + 中央立剑 + 绯红玫瑰墓园 + 哥特教堂拱门。
    //    黑白红三色强对比：深色=白袍主色对极黑虚空，浅色=象牙白袍画布 + 猩红玫瑰撞色；蚀刻线稿
    ThemePreset(
        id = "requiem",
        name = "亡者圣堂",
        desc = "白袍圣柩 · 玫瑰墓园",
        seed = Color(0xFFA8222A),
        secondary = Color(0xFF5F7263),
        tertiary = Color(0xFFB99856),
        lightBg = Color(0xFFEDE9DB),
        darkBg = Color(0xFF08090A),
        shape = "square",
        spacing = 1.1f,
        motionScale = 0.85f,
        stBody = Color(0xFFD6D2C2),
        stEm = Color(0xFF8E9488),
        stUnderline = Color(0xFFB9BDB3),
        stQuote = Color(0xFFC03A3A),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D1E2A22),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF0D130E),
        schemePrimary = Color(0xFFE6E1CF),
        schemeSecondary = Color(0xFFABAFA5),
        schemeTertiary = Color(0xFFC04A4A),
        // 哥特线稿：蚀刻排线 + 交叉 + 布点三件套（铜版画明暗全工艺）——多雷插画的线密度
        contrast = 1.45f,
        gem = Color(0xFFC0262E),
        metal = Color(0xFFB9BDB3),
        texture = TextureSpec(hatch = 1f, crossHatch = 0.5f, stipple = 0.55f),
        auraTop = Color(0xFF111C15),
        auraTopLight = Color(0xFFE6E0CE),
    ),
    // ⑤ 古海神殿：古希腊神殿 + 黑甲战士 + 深钴蓝海 + 赤红月 + 古代战船，复古奇幻插画的线稿肌理。
    //    深色=钴蓝夜海 + 大理石次色 + 赤月点缀；浅色=海雾白画布 + 钴蓝撞色 + 钴蓝薄暮天
    ThemePreset(
        id = "cobalt",
        name = "古海神殿",
        desc = "碧海神阶 · 赤月归帆",
        seed = Color(0xFF2E56B4),
        secondary = Color(0xFF3C4650),
        tertiary = Color(0xFFC22A1E),
        lightBg = Color(0xFFE8ECF2),
        darkBg = Color(0xFF0A1226),
        shape = "square",
        spacing = 1.12f,
        motionScale = 0.9f,
        stBody = Color(0xFFC6CBD8),
        stEm = Color(0xFF7E8CA0),
        stUnderline = Color(0xFF8FA0C0),
        stQuote = Color(0xFFD04434),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D1A2438),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF0E162C),
        schemePrimary = Color(0xFF6B90DC),
        schemeSecondary = Color(0xFFD5D1BF),
        schemeTertiary = Color(0xFFD04434),
        // 复古奇幻插画：布点 + 15° 排线 + 交叉（浅角斜线如海风）——版画教科书的组合
        contrast = 1.25f,
        gem = Color(0xFFCE3222),
        metal = Color(0xFF9C8A62),
        texture = TextureSpec(stipple = 0.55f, hatch = 0.8f, crossHatch = 0.35f, hatchAngle = 15f),
        auraTop = Color(0xFF1A2C55),
        auraTopLight = Color(0xFFC9D6EA),
    ),
    // ⑥ 禁忌档案馆（原创）：黑色石制图书馆 + 哥特拱顶 + 骷髅王冠徽记 + 巴洛克银金雕刻 +
    //    机械齿轮 + 红宝石微光 + 高窗外的红月与绯林。五幅画的元素在此全部化为馆藏。
    //    深色=烛光古金主色、红宝石微光、蓝宝石点缀；浅色=旧羊皮纸 + 古铜撞色 + 烛光暖天
    ThemePreset(
        id = "archive",
        name = "禁忌档案馆",
        desc = "王冠徽记 · 禁忌馆藏",
        seed = Color(0xFFA07C3E),
        // 旧铜（书架金属牌与机械齿轮）
        secondary = Color(0xFF8A7A5E),
        // 深蓝宝石（王冠上的第二类宝石）
        tertiary = Color(0xFF4A6A9C),
        lightBg = Color(0xFFF0E5CB),
        darkBg = Color(0xFF0F0C08),
        shape = "rounded",
        spacing = 1.2f,
        motionScale = 0.85f,
        stBody = Color(0xFFD6CCB4),
        stEm = Color(0xFF9A8E76),
        stUnderline = Color(0xFFB9A26C),
        stQuote = Color(0xFF7E9CC4),
        stUserBubble = Color(0x4D000000),
        stBotBubble = Color(0x4D241E10),
        stBorder = Color(0x80000000),
        stShadow = Color(0x80000000),
        stBlurTint = Color(0xFF14100A),
        schemePrimary = Color(0xFFC9A24B),
        schemeSecondary = Color(0xFFA89A7E),
        schemeTertiary = Color(0xFF7E9CC4),
        // 旧羊皮纸：草筋纤维 + 羊皮颗粒 + 尘点——中世纪手抄本的皮纸底
        contrast = 1.25f,
        gem = Color(0xFFC01F28),
        metal = Color(0xFF9C8A62),
        texture = TextureSpec(fiber = 0.7f, grain = 0.45f, stipple = 0.3f),
        auraTop = Color(0xFF2A1C0E),
        auraTopLight = Color(0xFFEBD9A8),
    ),
)

fun List<ThemePreset>.byId(id: String): ThemePreset = firstOrNull { it.id == id } ?: first()

/** 主题模式：跟随系统 / 浅色 / 深色。 */
enum class ThemeMode(val id: String, val label: String) {
    SYSTEM("system", "跟随系统"),
    LIGHT("light", "浅色"),
    DARK("dark", "深色"),
}
