package com.emberinn.app.ui.theme

import androidx.compose.ui.graphics.Color

/** README 预设主题（按中国人审美）：seed 生成整套 M3 配色，克制、低饱和。 */
data class ThemePreset(
    val id: String,
    val name: String,
    val desc: String,
    val seed: Color,
    val secondary: Color,
    val tertiary: Color,
    val lightBg: Color,
    val darkBg: Color,
    /** README 清单 9：六套主题各自性格——形状语言随预设变化（墨韵圆润/丹砂方正/琉璃浑圆）。 */
    val shape: String = "default",
    /** 间距节奏倍数（>1 更松散，<1 更紧凑）；默认 1.0。 */
    val spacing: Float = 1f,
    /** 动效速度倍数（>1 更快，<1 更慢）；默认 1.0。 */
    val motionScale: Float = 1f,
)

val ThemePresets: List<ThemePreset> = listOf(
    ThemePreset(
        id = "ink",
        name = "墨韵",
        desc = "水墨留白 · 朱砂点缀",
        seed = Color(0xFFB23A2A),
        secondary = Color(0xFF55524A),
        tertiary = Color(0xFF3D5A6C),
        lightBg = Color(0xFFF7F2E8),
        darkBg = Color(0xFF171513),
        shape = "rounded",
        spacing = 1.12f,
        motionScale = 0.85f,
    ),
    ThemePreset(
        id = "celadon",
        name = "青瓷",
        desc = "米白青墨 · 青绿点缀",
        seed = Color(0xFF2E7D6B),
        secondary = Color(0xFF5B6E6A),
        tertiary = Color(0xFFB49B6A),
        lightBg = Color(0xFFF5F3EC),
        darkBg = Color(0xFF15201D),
        shape = "rounded",
        spacing = 1.05f,
        motionScale = 0.95f,
    ),
    ThemePreset(
        id = "night",
        name = "夜航",
        desc = "雾白深蓝 · 琥珀灯",
        seed = Color(0xFFC98A2B),
        secondary = Color(0xFF5C6B7A),
        tertiary = Color(0xFF2C4A6E),
        lightBg = Color(0xFFF4F5F6),
        darkBg = Color(0xFF101820),
        shape = "default",
    ),
    ThemePreset(
        id = "cinnabar",
        name = "丹砂",
        desc = "纸白暖黑 · 丹红克制",
        seed = Color(0xFFC73E2B),
        secondary = Color(0xFF8A5A44),
        tertiary = Color(0xFFB08A3E),
        lightBg = Color(0xFFFBF4EF),
        darkBg = Color(0xFF1B1210),
        shape = "square",
        spacing = 0.92f,
        motionScale = 1.15f,
    ),
    ThemePreset(
        id = "glaze",
        name = "琉璃",
        desc = "冰白玻璃 · 紫蓝渐变",
        seed = Color(0xFF5B6CFF),
        secondary = Color(0xFF3FA7B8),
        tertiary = Color(0xFF9B6BFF),
        lightBg = Color(0xFFF5F7FB),
        darkBg = Color(0xFF10131A),
        shape = "circle",
        spacing = 0.95f,
        motionScale = 1.05f,
    ),
    ThemePreset(
        id = "paper",
        name = "简约纸感",
        desc = "象牙白 · 石墨中性",
        seed = Color(0xFF5A5A5E),
        secondary = Color(0xFF6E6E72),
        tertiary = Color(0xFF808488),
        lightBg = Color(0xFFF6F4EF),
        darkBg = Color(0xFF161616),
        shape = "default",
    ),
    // 酒馆官方（SillyTavern 1.18 默认 SmartTheme，public/style.css :root 逐值核对）：
    // 墨黑底 #171717 · 象牙文字 rgb(220,220,210) · 次要 rgb(145,145,145)
    // 青绿点缀 rgb(188,231,207) · 引用橙 rgb(225,138,36) · Noto Sans 15px / Noto Sans Mono
    ThemePreset(
        id = "st",
        name = "酒馆官方",
        desc = "SillyTavern 默认：墨黑底 · 象牙文字 · 青绿点缀",
        seed = Color(0xFF7FAF8C),
        secondary = Color(0xFF919191),
        tertiary = Color(0xFFE18A24),
        lightBg = Color(0xFFEDEBE2),
        darkBg = Color(0xFF171717),
        shape = "default",
    ),
    ThemePreset(
        id = "bamboo",
        name = "竹青",
        desc = "竹林晨光 · 青绿沉稳",
        seed = Color(0xFF4E8D6C),
        secondary = Color(0xFF7A8B6F),
        tertiary = Color(0xFFC9A227),
        lightBg = Color(0xFFF2F4EC),
        darkBg = Color(0xFF14201A),
        shape = "rounded",
        spacing = 1.05f,
        motionScale = 0.95f,
    ),
    ThemePreset(
        id = "dusk",
        name = "暮紫",
        desc = "黄昏暮色 · 紫调沉静",
        seed = Color(0xFF7C5CBF),
        secondary = Color(0xFF9A6FB0),
        tertiary = Color(0xFFD08770),
        lightBg = Color(0xFFF6F1F6),
        darkBg = Color(0xFF1A1522),
        shape = "rounded",
    ),
    ThemePreset(
        id = "mist",
        name = "晨雾",
        desc = "雾蓝清冷 · 晨光微暖",
        seed = Color(0xFF5E7FA3),
        secondary = Color(0xFF7D94A8),
        tertiary = Color(0xFFB08D57),
        lightBg = Color(0xFFF3F5F7),
        darkBg = Color(0xFF141B21),
        shape = "default",
        motionScale = 0.95f,
    ),
    ThemePreset(
        id = "sakura",
        name = "樱粉",
        desc = "樱色温柔 · 粉紫点缀",
        seed = Color(0xFFC96A8C),
        secondary = Color(0xFFB58A8E),
        tertiary = Color(0xFF8E7CC3),
        lightBg = Color(0xFFFBF2F4),
        darkBg = Color(0xFF20151A),
        shape = "rounded",
        spacing = 1.05f,
        motionScale = 1.05f,
    ),
)

fun List<ThemePreset>.byId(id: String): ThemePreset = firstOrNull { it.id == id } ?: first()

/** 主题模式：跟随系统 / 浅色 / 深色（README 默认浅色，深色跟随系统可选）。 */
enum class ThemeMode(val id: String, val label: String) {
    SYSTEM("system", "跟随系统"),
    LIGHT("light", "浅色"),
    DARK("dark", "深色"),
}
